### ISSUE TITLE
Upstreaming kak files

### ISSUE THREAD

**Issue by yerlaser** [TeddyDD/kakoune-dotfiles#2]
Hi,
I found your repo by google. Good work!
Are you planning to contribute your kak files to kakoune?
If not, do you mind if I others do it for you?
I am especially interested in groovy.kak.
Thanks!

**Comment by TeddyDD** [comment]
Hi. That was the plan but I don't time to polish things up.

>  If not, do you mind if I others do it for you?

Sure, go ahead. It's all Unlicense (except stuff I vendored but there should be comments indicating source - for example flygrep), so you can do whatever you want.

**Comment by yerlaser** [comment]
Cool. Thanks. Just FYI here's the PR: https://github.com/mawww/kakoune/pull/4463
I meanwhile added identation.
